use avian3d::prelude::*;
use bevy::{
    asset::RenderAssetUsages, mesh::Indices, prelude::*,
    render::render_resource::PrimitiveTopology as RenderPrimitiveTopology,
};

use crate::stations::{ResetStation, StationObject};

const PANEL_BACKGROUND: Color = Color::srgba(0.035, 0.05, 0.08, 0.94);
const PANEL_TEXT: Color = Color::srgb(0.87, 0.92, 0.98);
const SURFACE_POSITION: Vec3 = Vec3::new(6.0, 0.0, -1.0);
const SURFACE_WIDTH: f32 = 3.6;
const SURFACE_DEPTH: f32 = 1.5;
const SURFACE_BASE_HEIGHT: f32 = 0.0;
const DROP_START_Y: f32 = 4.5;
const DROP_RADIUS: f32 = 0.18;
const SLIDER_START: Vec3 = Vec3::new(-1.45, 2.6, 0.0);
const SLIDER_SPEED: f32 = 0.65;

/// The regions used to demonstrate contacts on separate parts of the mesh.
#[derive(Component, Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum MeshSurfacePart {
    LeftRidge,
    CenterDip,
    RightSlope,
}

impl MeshSurfacePart {
    const ALL: [Self; 3] = [Self::LeftRidge, Self::CenterDip, Self::RightSlope];

    const fn label(self) -> &'static str {
        match self {
            Self::LeftRidge => "LEFT RIDGE",
            Self::CenterDip => "CENTER DIP",
            Self::RightSlope => "RIGHT SLOPE",
        }
    }

    const fn local_position(self) -> Vec3 {
        match self {
            Self::LeftRidge => Vec3::new(-1.35, DROP_START_Y, -0.42),
            Self::CenterDip => Vec3::new(0.0, DROP_START_Y, 0.0),
            Self::RightSlope => Vec3::new(1.35, DROP_START_Y, 0.42),
        }
    }

    const fn color(self) -> Color {
        match self {
            Self::LeftRidge => Color::srgb(0.35, 0.82, 1.0),
            Self::CenterDip => Color::srgb(0.98, 0.72, 0.22),
            Self::RightSlope => Color::srgb(0.45, 0.92, 0.5),
        }
    }
}

/// Marks the visible irregular surface whose collider is generated by Avian.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MeshColliderLabSurface;

/// Added when Avian finishes generating the surface's mesh collider.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MeshColliderGenerated;

/// Marks a locked drop placed over one region of the generated mesh.
#[derive(Component, Clone, Copy, Debug, Eq, PartialEq)]
pub struct MeshColliderLabDrop {
    pub part: MeshSurfacePart,
}

/// Marks the free-moving body that slides over the irregular surface.
#[derive(Component, Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct MeshColliderLabSlider;

/// Owns station C's irregular mesh and Avian-generated mesh-collider trials.
pub struct MeshColliderStationPlugin;

impl Plugin for MeshColliderStationPlugin {
    fn build(&self, app: &mut App) {
        app.add_message::<ResetStation>()
            .add_systems(
                Startup,
                (spawn_mesh_collider_lab, spawn_mesh_collider_station_ui),
            )
            .add_systems(
                Update,
                draw_mesh_collider_labels.run_if(resource_exists::<GizmoConfigStore>),
            )
            .add_systems(PostUpdate, reset_mesh_collider_lab);
    }
}

fn spawn_mesh_collider_lab(
    mut commands: Commands,
    mut meshes: Option<ResMut<Assets<Mesh>>>,
    mut materials: Option<ResMut<Assets<StandardMaterial>>>,
) {
    let Some(meshes) = meshes.as_mut() else {
        return;
    };
    let mesh = meshes.add(irregular_surface_mesh());
    let material = materials
        .as_mut()
        .map(|materials| materials.add(Color::srgb(0.23, 0.56, 0.42)));

    let mut surface = commands.spawn((
        MeshColliderLabSurface,
        RigidBody::Static,
        // Avian waits for Mesh3d's asset and inserts the actual Collider at runtime.
        ColliderConstructor::TrimeshFromMesh,
        Transform::from_translation(SURFACE_POSITION),
        Name::new("Mesh Collider Lab - Irregular Surface"),
    ));
    surface.observe(mark_mesh_collider_generated);
    if let Some(material) = material {
        surface.insert((Mesh3d(mesh), MeshMaterial3d(material)));
    } else {
        surface.insert(Mesh3d(mesh));
    }

    for part in MeshSurfacePart::ALL {
        let local_position = part.local_position();
        let position = SURFACE_POSITION + local_position;
        let transform = Transform::from_translation(position);
        let drop_mesh = meshes.add(Sphere::new(DROP_RADIUS));
        let drop_material = materials
            .as_mut()
            .map(|materials| materials.add(part.color().with_luminance(0.78)));
        let mut drop = commands.spawn((
            MeshColliderLabDrop { part },
            StationObject::new('C', transform),
            RigidBody::Dynamic,
            Collider::sphere(DROP_RADIUS),
            Friction::new(0.28),
            Restitution::ZERO,
            SleepingDisabled,
            LockedAxes::new()
                .lock_translation_x()
                .lock_translation_z()
                .lock_rotation_x()
                .lock_rotation_y()
                .lock_rotation_z(),
            transform,
            Name::new(format!("Mesh Collider Drop - {}", part.label())),
        ));
        drop.insert(Mesh3d(drop_mesh));
        if let Some(material) = drop_material {
            drop.insert(MeshMaterial3d(material));
        }
    }

    let slider_position = SURFACE_POSITION + SLIDER_START;
    let slider_transform = Transform::from_translation(slider_position);
    let slider_mesh = meshes.add(Sphere::new(DROP_RADIUS * 1.2));
    let slider_material = materials
        .as_mut()
        .map(|materials| materials.add(Color::srgb(0.98, 0.38, 0.25)));
    let mut slider = commands.spawn((
        MeshColliderLabSlider,
        StationObject::new('C', slider_transform)
            .with_velocities(Vec3::X * SLIDER_SPEED, Vec3::ZERO),
        RigidBody::Dynamic,
        Collider::sphere(DROP_RADIUS * 1.2),
        Friction::new(0.2),
        Restitution::ZERO,
        SleepingDisabled,
        LinearVelocity(Vec3::X * SLIDER_SPEED),
        slider_transform,
        Name::new("Mesh Collider Slider"),
    ));
    slider.insert(Mesh3d(slider_mesh));
    if let Some(material) = slider_material {
        slider.insert(MeshMaterial3d(material));
    }
}

fn mark_mesh_collider_generated(ready: On<ColliderConstructorReady>, mut commands: Commands) {
    commands.entity(ready.entity).insert(MeshColliderGenerated);
}

fn irregular_surface_mesh() -> Mesh {
    // Three rows and five columns make a shallow, closed, non-planar surface.
    // The varying ridge heights are intentionally visible and are also the data
    // Avian consumes when it builds the triangle-mesh collider.
    const X: [f32; 5] = [
        -SURFACE_WIDTH * 0.5,
        -SURFACE_WIDTH * 0.25,
        0.0,
        SURFACE_WIDTH * 0.25,
        SURFACE_WIDTH * 0.5,
    ];
    const Z: [f32; 3] = [-SURFACE_DEPTH * 0.5, 0.0, SURFACE_DEPTH * 0.5];
    const HEIGHTS: [[f32; 3]; 5] = [
        [1.55, 1.82, 1.5],
        [1.02, 1.28, 0.98],
        [0.55, 0.82, 0.62],
        [0.98, 1.32, 0.92],
        [0.42, 0.62, 0.5],
    ];

    let top_count = X.len() * Z.len();
    let mut positions = Vec::with_capacity(top_count * 2);
    for (x_index, x) in X.iter().enumerate() {
        for (z_index, z) in Z.iter().enumerate() {
            positions.push([*x, HEIGHTS[x_index][z_index], *z]);
        }
    }
    for x in X {
        for z in Z {
            positions.push([x, SURFACE_BASE_HEIGHT, z]);
        }
    }

    let index = |x: usize, z: usize| -> u32 { (x * Z.len() + z) as u32 };
    let bottom = |x: usize, z: usize| -> u32 { top_count as u32 + index(x, z) };
    let mut indices = Vec::new();

    // Top quads, with the winding facing upward.
    for x in 0..X.len() - 1 {
        for z in 0..Z.len() - 1 {
            let a = index(x, z);
            let b = index(x + 1, z);
            let c = index(x + 1, z + 1);
            let d = index(x, z + 1);
            indices.extend_from_slice(&[a, d, b, b, d, c]);
        }
    }

    // Bottom and perimeter faces close the triangle mesh, keeping the collider
    // useful if a body reaches an edge of the demonstration surface.
    for x in 0..X.len() - 1 {
        for z in 0..Z.len() - 1 {
            let a = bottom(x, z);
            let b = bottom(x + 1, z);
            let c = bottom(x + 1, z + 1);
            let d = bottom(x, z + 1);
            indices.extend_from_slice(&[a, b, d, b, c, d]);
        }
    }
    for x in 0..X.len() - 1 {
        let top_a = index(x, 0);
        let top_b = index(x + 1, 0);
        let bottom_a = bottom(x, 0);
        let bottom_b = bottom(x + 1, 0);
        indices.extend_from_slice(&[top_a, top_b, bottom_a, top_b, bottom_b, bottom_a]);

        let top_a = index(x, Z.len() - 1);
        let top_b = index(x + 1, Z.len() - 1);
        let bottom_a = bottom(x, Z.len() - 1);
        let bottom_b = bottom(x + 1, Z.len() - 1);
        indices.extend_from_slice(&[top_a, bottom_a, top_b, top_b, bottom_a, bottom_b]);
    }
    for z in 0..Z.len() - 1 {
        let top_a = index(0, z);
        let top_b = index(0, z + 1);
        let bottom_a = bottom(0, z);
        let bottom_b = bottom(0, z + 1);
        indices.extend_from_slice(&[top_a, bottom_a, top_b, top_b, bottom_a, bottom_b]);

        let top_a = index(X.len() - 1, z);
        let top_b = index(X.len() - 1, z + 1);
        let bottom_a = bottom(X.len() - 1, z);
        let bottom_b = bottom(X.len() - 1, z + 1);
        indices.extend_from_slice(&[top_a, top_b, bottom_a, top_b, bottom_b, bottom_a]);
    }

    let mut mesh = Mesh::new(
        RenderPrimitiveTopology::TriangleList,
        RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
    )
    .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, positions)
    .with_inserted_indices(Indices::U32(indices));
    mesh.compute_normals();
    mesh
}

#[derive(Component)]
struct MeshColliderStationPanel;

fn spawn_mesh_collider_station_ui(mut commands: Commands) {
    commands
        .spawn((
            Node {
                position_type: PositionType::Absolute,
                left: px(800.0),
                top: px(272.0),
                width: px(350.0),
                padding: UiRect::all(px(14.0)),
                flex_direction: FlexDirection::Column,
                row_gap: px(4.0),
                ..default()
            },
            BackgroundColor(PANEL_BACKGROUND),
            MeshColliderStationPanel,
            Name::new("Mesh Collider Station Controls"),
        ))
        .with_children(|parent| {
            parent.spawn((
                Text::new("C — MESH COLLIDER GENERATION"),
                TextFont::from_font_size(18.0),
                TextColor(PANEL_TEXT),
            ));
            parent.spawn((
                Text::new(
                    "The irregular green mesh is the presentation geometry. Avian generates its orange F1 triangle-mesh collider at runtime.",
                ),
                TextFont::from_font_size(12.0),
                TextColor(PANEL_TEXT),
                Node {
                    margin: UiRect::bottom(px(6.0)),
                    ..default()
                },
            ));
            for part in MeshSurfacePart::ALL {
                parent.spawn((
                    Text::new(format!("{}    drop + contact test", part.label())),
                    TextFont::from_font_size(13.0),
                    TextColor(part.color()),
                ));
            }
            parent.spawn((
                Text::new("RED SLIDER    falls, then travels across the ridges"),
                TextFont::from_font_size(13.0),
                TextColor(Color::srgb(0.98, 0.38, 0.25)),
            ));
            parent.spawn((
                Text::new("F1: show generated collider   R: reset station C"),
                TextFont::from_font_size(12.0),
                TextColor(PANEL_TEXT),
            ));
        });
}

fn draw_mesh_collider_labels(
    mut gizmos: Gizmos,
    surfaces: Query<(&Transform, Option<&MeshColliderGenerated>), With<MeshColliderLabSurface>>,
    drops: Query<(&MeshColliderLabDrop, &Transform)>,
    sliders: Query<&Transform, With<MeshColliderLabSlider>>,
) {
    for (transform, generated) in &surfaces {
        let status = if generated.is_some() {
            "AVIAN TRIMESH\nF1 COLLIDER READY"
        } else {
            "GENERATING\nTRIMESH COLLIDER"
        };
        gizmos.text(
            Isometry3d::new(
                transform.translation + Vec3::new(0.0, 2.25, 0.0),
                Quat::IDENTITY,
            ),
            status,
            0.3,
            Vec2::ZERO,
            Color::srgb(1.0, 0.42, 0.15),
        );
    }

    for (drop, transform) in &drops {
        gizmos.text(
            Isometry3d::new(transform.translation + Vec3::Y * 0.3, Quat::IDENTITY),
            &format!("{} DROP", drop.part.label()),
            0.2,
            Vec2::ZERO,
            drop.part.color(),
        );
    }

    for transform in &sliders {
        gizmos.text(
            Isometry3d::new(transform.translation + Vec3::Y * 0.34, Quat::IDENTITY),
            "SLIDING BODY",
            0.22,
            Vec2::ZERO,
            Color::srgb(0.98, 0.38, 0.25),
        );
    }
}

#[allow(clippy::type_complexity)]
fn reset_mesh_collider_lab(
    mut requests: MessageReader<ResetStation>,
    mut objects: Query<
        (
            &StationObject,
            &mut Transform,
            &mut Position,
            &mut Rotation,
            &mut LinearVelocity,
            &mut AngularVelocity,
        ),
        Or<(With<MeshColliderLabDrop>, With<MeshColliderLabSlider>)>,
    >,
) {
    if !requests.read().any(|request| request.code == 'C') {
        return;
    }

    for (
        initial,
        mut transform,
        mut position,
        mut rotation,
        mut linear_velocity,
        mut angular_velocity,
    ) in &mut objects
    {
        *transform = initial.initial_transform;
        position.0 = initial.initial_transform.translation;
        rotation.0 = initial.initial_transform.rotation;
        linear_velocity.0 = initial.initial_linear_velocity;
        angular_velocity.0 = initial.initial_angular_velocity;
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use std::time::Duration;

    use bevy::{
        gizmos::GizmoPlugin, input::InputPlugin, mesh::MeshPlugin, time::TimeUpdateStrategy,
    };

    use super::*;
    use crate::collider_debug::ColliderDebugPlugin;

    const PHYSICS_STEP: f32 = 1.0 / 60.0;

    fn mesh_app(with_debug: bool) -> App {
        let mut app = App::new();
        app.add_plugins((
            MinimalPlugins,
            InputPlugin,
            AssetPlugin::default(),
            MeshPlugin,
            PhysicsPlugins::default(),
            MeshColliderStationPlugin,
        ));
        if with_debug {
            app.add_plugins((GizmoPlugin, ColliderDebugPlugin));
        }
        app.insert_resource(Assets::<Mesh>::default())
            .insert_resource(Assets::<StandardMaterial>::default())
            .insert_resource(Gravity(Vec3::new(0.0, -9.81, 0.0)))
            .insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f32(
                PHYSICS_STEP,
            )));
        app.finish();
        app
    }

    fn run_steps(app: &mut App, steps: usize) {
        for _ in 0..steps {
            app.update();
        }
    }

    fn entities_by_part(app: &mut App) -> HashMap<MeshSurfacePart, Entity> {
        let world = app.world_mut();
        let mut drops = world.query::<(Entity, &MeshColliderLabDrop)>();
        drops
            .iter(world)
            .map(|(entity, drop)| (drop.part, entity))
            .collect()
    }

    #[test]
    fn irregular_mesh_is_visible_and_has_a_runtime_generated_collider() {
        let mut app = mesh_app(false);
        app.update();

        let world = app.world_mut();
        let mut surfaces = world.query::<(
            &MeshColliderLabSurface,
            &Mesh3d,
            &RigidBody,
            &Collider,
            &MeshColliderGenerated,
            &Name,
        )>();
        let (surface, _, body, _, generated, name) = surfaces.single(world).expect("surface");
        assert_eq!(*surface, MeshColliderLabSurface);
        assert_eq!(*body, RigidBody::Static);
        assert_eq!(*generated, MeshColliderGenerated);
        assert!(name.as_str().contains("Irregular Surface"));
    }

    #[test]
    fn avian_generates_a_trimesh_collider_from_the_irregular_mesh() {
        let mut app = mesh_app(false);
        app.update();

        let (mesh_handle, vertex_count, generated) = {
            let world = app.world_mut();
            let mut surfaces = world.query::<(
                &MeshColliderLabSurface,
                &Mesh3d,
                &Collider,
                &MeshColliderGenerated,
            )>();
            let (_, mesh, collider, generated) = surfaces.single(world).expect("generated surface");
            (
                mesh.0.clone(),
                collider.shape().as_trimesh().unwrap().vertices().len(),
                *generated,
            )
        };
        assert!(
            app.world()
                .resource::<Assets<Mesh>>()
                .get(&mesh_handle)
                .is_some()
        );
        assert_eq!(vertex_count, 30);
        assert_eq!(generated, MeshColliderGenerated);
    }

    #[test]
    fn drops_contact_multiple_irregular_mesh_regions() {
        let mut app = mesh_app(false);
        app.update();

        let surface = {
            let world = app.world_mut();
            world
                .query_filtered::<Entity, With<MeshColliderLabSurface>>()
                .single(world)
                .expect("surface")
        };
        let drops = entities_by_part(&mut app);
        let initial_y: HashMap<_, _> = drops
            .iter()
            .map(|(part, entity)| {
                (
                    *part,
                    app.world()
                        .entity(*entity)
                        .get::<Position>()
                        .expect("drop position")
                        .0
                        .y,
                )
            })
            .collect();

        run_steps(&mut app, 240);

        for part in MeshSurfacePart::ALL {
            let drop = drops[&part];
            let final_position = app
                .world()
                .entity(drop)
                .get::<Position>()
                .expect("drop position")
                .0;
            assert!(
                final_position.y < initial_y[&part] - 1.0,
                "{} did not fall: {final_position:?}",
                part.label()
            );
            assert!(
                app.world()
                    .resource::<ContactGraph>()
                    .contains(drop, surface),
                "{} did not contact the generated mesh",
                part.label()
            );
        }
    }

    #[test]
    fn free_body_slides_across_the_irregular_surface() {
        let mut app = mesh_app(false);
        app.update();
        let slider = {
            let world = app.world_mut();
            world
                .query_filtered::<Entity, With<MeshColliderLabSlider>>()
                .single(world)
                .expect("slider")
        };
        let surface = {
            let world = app.world_mut();
            world
                .query_filtered::<Entity, With<MeshColliderLabSurface>>()
                .single(world)
                .expect("surface")
        };
        let initial_position = app.world().entity(slider).get::<Position>().unwrap().0;

        run_steps(&mut app, 240);

        let final_position = app.world().entity(slider).get::<Position>().unwrap().0;
        assert!(final_position.y < initial_position.y - 1.0);
        assert!(
            final_position.x > initial_position.x + 0.2,
            "slider did not travel over the mesh: {initial_position:?} -> {final_position:?}"
        );
        assert!(
            app.world()
                .resource::<ContactGraph>()
                .contains(slider, surface)
        );
    }

    #[test]
    fn f1_enables_the_generated_collider_wireframe_without_hiding_meshes() {
        let mut app = mesh_app(true);
        app.update();
        assert!(
            !app.world()
                .resource::<GizmoConfigStore>()
                .config::<PhysicsGizmos>()
                .1
                .hide_meshes
        );
        assert_eq!(
            app.world()
                .resource::<GizmoConfigStore>()
                .config::<PhysicsGizmos>()
                .1
                .collider_color,
            None
        );

        app.world_mut()
            .resource_mut::<Messages<bevy::input::keyboard::KeyboardInput>>()
            .write(bevy::input::keyboard::KeyboardInput {
                key_code: KeyCode::F1,
                logical_key: bevy::input::keyboard::Key::F1,
                state: bevy::input::ButtonState::Pressed,
                text: None,
                repeat: false,
                window: Entity::PLACEHOLDER,
            });
        app.update();

        assert!(
            !app.world()
                .resource::<GizmoConfigStore>()
                .config::<PhysicsGizmos>()
                .1
                .hide_meshes
        );
        assert_eq!(
            app.world()
                .resource::<GizmoConfigStore>()
                .config::<PhysicsGizmos>()
                .1
                .collider_color,
            Some(Color::srgb(1.0, 0.35, 0.1))
        );
    }
}
